### ISSUE TITLE
Occasionally can't restart SR300 with /camera/driver/force_power service

### ISSUE THREAD

**Issue by mattcorsaro1** [realsenseai/realsense-ros#130]
| Version | Your Configuration |
| :-- | :-- |
| Operating System | Ubuntu 14.04.5 LTS |
| Kernel | 4.4.0-38-generic |
| Backend | video4linux |
| ROS | indigo |
| ROS RealSense | 1.5.0 |
| librealsense | 0.9.1 |
| Camera Type-Firmware | 3.15.0.0 |

---
### Expected Behavior

Launch `sr300_nodelet_rgbd.launch` and another node from a launch file. In the other node (Python), initialize some variables, wait for three seconds, then force camera power off with

```
from realsense_camera import srv
camera_forcepower_service = rospy.ServiceProxy('/camera/driver/force_power', srv.ForcePower)
camera_forcepower_service(False)
```

Throughout the script, turn the power back on with camera_forcepower_service(True), then off with camera_forcepower_service(False) after reading a cloud.
### Actual Behavior

Most of the time, it works as expected. Once in a while, I won't be able to restart the camera within the middle of my script, even after it's been started and stopped successfully. I'll get an error like this:

```
[ INFO] [1476720876.616341805]: /camera/driver - Starting camera
[ERROR] [1476720876.621235305]: /camera/driver - Error calling rs_start_device ( device:0x2614538 ): 
VIDIOC_S_PARM error 5, Input/output error 

terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::lock_error> >'
  what():  boost: mutex lock failed in pthread_mutex_lock: Invalid argument
[camera/camera_nodelet_manager-1] process has died [pid 11388, exit code -6, cmd /opt/ros/indigo/lib/nodelet/nodelet manager __name:=camera_nodelet_manager __log:=/home/ur5/.ros/log/b1689f24-9482-11e6-b0d0
-4ccc6a230519/camera-camera_nodelet_manager-1.log].
log file: /home/ur5/.ros/log/b1689f24-9482-11e6-b0d0-4ccc6a230519/camera-camera_nodelet_manager-1*.log
[camera/driver-2] process has finished cleanly
log file: /home/ur5/.ros/log/b1689f24-9482-11e6-b0d0-4ccc6a230519/camera-driver-2*.log

```

I then have to reboot the computer to access the camera again. Before rebooting, lsusb doesn't list the camera as connected, even when it's plugged in.
### Steps to Reproduce

Launch camera nodelet with `roslaunch realsense_camera sr300_nodelet_rgbd.launch`
Shutdown in another node with the following Python code:

```
from realsense_camera import srv
camera_forcepower_service = rospy.ServiceProxy('/camera/driver/force_power', srv.ForcePower)
camera_forcepower_service(False)
```

Later in the same Python script, start the camera again with `camera_forcepower_service(True)`
Shut the camera off again after reading an image.

**Comment by mattcorsaro1** [comment]
Another error, although this one can be fixed by unplugging the camera and plugging it in again:

```
[ INFO] [1476724194.379703393]: /camera/driver - Starting camera
[ INFO] [1476724194.394910006]: /camera/driver - Camera Started Succesfully
[ERROR] [1476724199.395296647]: /camera/driver - Error calling rs_wait_for_frames ( device:0x1f97858 ): 
Timeout waiting for frames. 

terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::lock_error> >'
  what():  boost: mutex lock failed in pthread_mutex_lock: Invalid argument
[camera/camera_nodelet_manager-1] process has died [pid 8305, exit code -6, cmd /opt/ros/indigo/lib/nodelet/nodelet manager __name:=camera_nodelet_manager __log:=/home/ur5/.ros/log/d7b130f8-948a-11e6-9915-4ccc6a230519/camera-camera_nodelet_manager-1.log].
log file: /home/ur5/.ros/log/d7b130f8-948a-11e6-9915-4ccc6a230519/camera-camera_nodelet_manager-1*.log
[camera/driver-2] process has finished cleanly
log file: /home/ur5/.ros/log/d7b130f8-948a-11e6-9915-4ccc6a230519/camera-driver-2*.log
```

**Comment by rjingar** [comment]
Hi @mattcorsaro1 

I tried to start/stop the camera multiple times using your script and it always works for me. I unable to reproduce the issue. How frequently you are seeing the issue? Also, are you seeing the issue regardless of whether there is a subscriber or not?

**Comment by mattcorsaro1** [comment]
It happens about 5% of the time. Here's my script to recreate the issue:

camera_test.launch:

```
<launch>
    <include file="$(find realsense_camera)/launch/sr300_nodelet_rgbd.launch"/>

    <group>
        <node name="camera_test" pkg="pkg_name" type="camera_test.py" output="screen">
        </node>
    </group>

</launch>
```

camera_test.py:

```
#!/usr/bin/env python

'''
Turn the camera on and off repeatedly
'''

import rospy
from realsense_camera import srv

def main():
  camera_forcepower_service = rospy.ServiceProxy('/camera/driver/force_power', srv.ForcePower)
  #camera_ispowered_service = rospy.ServiceProxy('/camera/driver/is_powered', srv.IsPowered)

  rospy.sleep(3.0)
  camera_forcepower_service(False)

  while True:
    camera_forcepower_service(True)
    rospy.sleep(0.01)
    camera_forcepower_service(False)

if __name__ == '__main__':
  main()
```

And here's the output:

```
ur5@UR5:~/ur5_ws$ roslaunch ur_grasping camera_test.launch 
... logging to /home/ur5/.ros/log/8c6d86ce-96e6-11e6-96fb-4ccc6a230519/roslaunch-UR5-28089.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://UR5:36803/

SUMMARY
========

PARAMETERS
 * /camera/camera_nodelet_manager/num_worker_threads: 4
 * /camera/depth_rectify_depth/interpolation: 0
 * /camera/disparity_depth/max_range: 4.0
 * /camera/disparity_depth/min_range: 0.5
 * /camera/disparity_registered_sw/max_range: 4.0
 * /camera/disparity_registered_sw/min_range: 0.5
 * /camera/driver/base_frame_id: camera_link
 * /camera/driver/camera_type: SR300
 * /camera/driver/color_fps: 30
 * /camera/driver/color_frame_id: camera_rgb_frame
 * /camera/driver/color_height: 480
 * /camera/driver/color_optical_frame_id: camera_rgb_optica...
 * /camera/driver/color_width: 640
 * /camera/driver/depth_fps: 30
 * /camera/driver/depth_frame_id: camera_depth_frame
 * /camera/driver/depth_height: 480
 * /camera/driver/depth_optical_frame_id: camera_depth_opti...
 * /camera/driver/depth_width: 640                                                                                                                                                                 
 * /camera/driver/enable_color: True
 * /camera/driver/enable_depth: True
 * /camera/driver/enable_pointcloud: False
 * /camera/driver/enable_tf: True
 * /camera/driver/ir2_frame_id: camera_ir2_frame
 * /camera/driver/ir_frame_id: camera_ir_frame
 * /camera/driver/mode: manual
 * /camera/driver/serial_no: 
 * /camera/driver/usb_port_id: 
 * /camera/points_xyzrgb_sw_registered/queue_size: 100
 * /rosdistro: indigo
 * /rosversion: 1.11.20

NODES
  /camera/
    camera_nodelet_manager (nodelet/nodelet)
    depth_metric (nodelet/nodelet)
    depth_metric_rect (nodelet/nodelet)
    depth_points (nodelet/nodelet)
    depth_rectify_depth (nodelet/nodelet)
    depth_registered_sw_metric_rect (nodelet/nodelet)
    disparity_depth (nodelet/nodelet)
    disparity_registered_sw (nodelet/nodelet)
    driver (nodelet/nodelet)
    ir_rectify_ir (nodelet/nodelet)
    points_xyzrgb_sw_registered (nodelet/nodelet)
    register_depth_rgb (nodelet/nodelet)
    rgb_debayer (nodelet/nodelet)
    rgb_rectify_color (nodelet/nodelet)
    rgb_rectify_mono (nodelet/nodelet)
  /
    camera_test (ur_grasping/camera_test.py)

ROS_MASTER_URI=http://localhost:11311

core service [/rosout] found
process[camera/camera_nodelet_manager-1]: started with pid [28107]
process[camera/driver-2]: started with pid [28108]
process[camera/rgb_debayer-3]: started with pid [28109]
process[camera/rgb_rectify_mono-4]: started with pid [28110]
process[camera/rgb_rectify_color-5]: started with pid [28111]
process[camera/ir_rectify_ir-6]: started with pid [28123]
process[camera/depth_rectify_depth-7]: started with pid [28135]
process[camera/depth_metric_rect-8]: started with pid [28141]
process[camera/depth_metric-9]: started with pid [28151]
process[camera/depth_points-10]: started with pid [28160]
process[camera/register_depth_rgb-11]: started with pid [28175]
process[camera/points_xyzrgb_sw_registered-12]: started with pid [28189]
process[camera/depth_registered_sw_metric_rect-13]: started with pid [28198]
process[camera/disparity_depth-14]: started with pid [28214]
process[camera/disparity_registered_sw-15]: started with pid [28223]
process[camera_test-16]: started with pid [28231]
[ INFO] [1476987939.166910630]: Initializing nodelet with 4 worker threads.
[ INFO] [1476987939.762231446]: /camera/driver - Detected the following cameras:
                                - Serial No: 612201004240, USB Port ID: 8-1, Name: Intel RealSense SR300, Firmware: 3.15.0.0
[ INFO] [1476987939.762287528]: /camera/driver - Connecting to camera with Serial No: 612201004240, USB Port ID: 8-1
[ INFO] [1476987940.962142552]: /camera/driver - Setting static camera options                                                                                                                     
[ INFO] [1476987940.968484839]: /camera/driver - Enabling Color in manual mode
[ INFO] [1476987940.969194356]: /camera/driver - Enabling Depth in manual mode
[ INFO] [1476987940.969678286]: /camera/driver - Enabling IR in manual mode
[ INFO] [1476987940.970185753]: /camera/driver - Starting camera
[ INFO] [1476987940.990730056]: /camera/driver - Publishing camera transforms
[ INFO] [1476987940.990969262]: /camera/driver - Setting dynamic camera options
[ INFO] [1476987942.257525505]: /camera/driver - Stopping camera
[ INFO] [1476987942.271215654]: /camera/driver - Camera Stopped Succesfully
[ INFO] [1476987942.273029781]: /camera/driver - Camera is already Stopped
[ INFO] [1476987942.275696182]: /camera/driver - Starting camera
[ INFO] [1476987942.296558821]: /camera/driver - Camera Started Succesfully
[ INFO] [1476987942.558857260]: /camera/driver - Camera is already Started
[ INFO] [1476987942.594468911]: /camera/driver - Camera is already Started
[ INFO] [1476987942.614077410]: /camera/driver - Camera is already Started
[ INFO] [1476987942.647554712]: /camera/driver - Camera is already Started
[ INFO] [1476987942.680880318]: /camera/driver - Camera is already Started
[ INFO] [1476987942.714296090]: /camera/driver - Stopping camera
[ INFO] [1476987942.727472207]: /camera/driver - Camera Stopped Succesfully
[ INFO] [1476987942.738525987]: /camera/driver - Camera is already Stopped
[ INFO] [1476987942.739937828]: /camera/driver - Starting camera
[ INFO] [1476987942.758046975]: /camera/driver - Camera Started Succesfully
[ INFO] [1476987942.964799943]: /camera/driver - Camera is already Started
[ INFO] [1476987942.998020089]: /camera/driver - Camera is already Started
[ INFO] [1476987943.031388578]: /camera/driver - Stopping camera
[ INFO] [1476987943.044545558]: /camera/driver - Camera Stopped Succesfully
[ INFO] [1476987943.055800761]: /camera/driver - Camera is already Stopped
[ INFO] [1476987943.057134380]: /camera/driver - Starting camera
[ INFO] [1476987943.075611380]: /camera/driver - Camera Started Succesfully
[ INFO] [1476987943.304713070]: /camera/driver - Stopping camera
[ INFO] [1476987943.317551295]: /camera/driver - Camera Stopped Succesfully
[ INFO] [1476987943.318609041]: /camera/driver - Starting camera
[ INFO] [1476987943.337138702]: /camera/driver - Camera Started Succesfully
[ INFO] [1476987943.556267615]: /camera/driver - Camera is already Started
[ INFO] [1476987943.589441666]: /camera/driver - Camera is already Started
[ INFO] [1476987943.623129679]: /camera/driver - Stopping camera
[ INFO] [1476987943.635581402]: /camera/driver - Camera Stopped Succesfully
[ INFO] [1476987943.636272621]: /camera/driver - Starting camera
[ INFO] [1476987943.654424370]: /camera/driver - Camera Started Succesfully
[ INFO] [1476987943.873125715]: /camera/driver - Camera is already Started
[ INFO] [1476987943.906472134]: /camera/driver - Camera is already Started
[ INFO] [1476987943.940134236]: /camera/driver - Camera is already Started
[ INFO] [1476987943.973475278]: /camera/driver - Stopping camera
[ INFO] [1476987943.986520372]: /camera/driver - Camera Stopped Succesfully
[ INFO] [1476987943.986721236]: /camera/driver - Starting camera
[ INFO] [1476987944.004978935]: /camera/driver - Camera Started Succesfully
[ INFO] [1476987944.222336603]: /camera/driver - Camera is already Started
[ INFO] [1476987944.255628406]: /camera/driver - Stopping camera
[ INFO] [1476987944.268652409]: /camera/driver - Camera Stopped Succesfully
[ INFO] [1476987944.269245501]: /camera/driver - Starting camera
[ INFO] [1476987944.287794717]: /camera/driver - Camera Started Succesfully
[ INFO] [1476987944.505351922]: /camera/driver - Camera is already Started
[ INFO] [1476987944.538272240]: /camera/driver - Camera is already Started
[ INFO] [1476987944.571895161]: /camera/driver - Camera is already Started
[ INFO] [1476987944.605289840]: /camera/driver - Camera is already Started
[ INFO] [1476987944.638682355]: /camera/driver - Camera is already Started
[ INFO] [1476987944.672040647]: /camera/driver - Camera is already Started
[ INFO] [1476987944.705354171]: /camera/driver - Stopping camera                                                                                                                                   
[ INFO] [1476987944.718977901]: /camera/driver - Camera Stopped Succesfully
[ INFO] [1476987944.720850485]: /camera/driver - Starting camera
[ INFO] [1476987944.740341511]: /camera/driver - Camera Started Succesfully
[ INFO] [1476987944.954966988]: /camera/driver - Camera is already Started
[ INFO] [1476987944.988216189]: /camera/driver - Camera is already Started
[ INFO] [1476987945.021884786]: /camera/driver - Camera is already Started
[ INFO] [1476987945.055277859]: /camera/driver - Camera is already Started
[ INFO] [1476987945.088754951]: /camera/driver - Camera is already Started
[ INFO] [1476987945.122016583]: /camera/driver - Camera is already Started
[ INFO] [1476987945.155439688]: /camera/driver - Camera is already Started
[ INFO] [1476987945.188850292]: /camera/driver - Camera is already Started
[ INFO] [1476987945.222198596]: /camera/driver - Camera is already Started
[ INFO] [1476987945.255581263]: /camera/driver - Camera is already Started
[ INFO] [1476987945.288987886]: /camera/driver - Camera is already Started
[ INFO] [1476987945.322382635]: /camera/driver - Camera is already Started
[ INFO] [1476987945.355725912]: /camera/driver - Camera is already Started
[ INFO] [1476987945.389159772]: /camera/driver - Camera is already Started
[ INFO] [1476987945.422526236]: /camera/driver - Camera is already Started
[ INFO] [1476987945.455972598]: /camera/driver - Camera is already Started
[ INFO] [1476987945.489275297]: /camera/driver - Camera is already Started
[ INFO] [1476987945.522934884]: /camera/driver - Camera is already Started
[ INFO] [1476987945.556088891]: /camera/driver - Camera is already Started
[ INFO] [1476987945.589416453]: /camera/driver - Camera is already Started
[ INFO] [1476987945.622799399]: /camera/driver - Stopping camera
[ INFO] [1476987945.635349110]: /camera/driver - Camera Stopped Succesfully
[ INFO] [1476987945.637346291]: /camera/driver - Starting camera
[ INFO] [1476987945.654939031]: /camera/driver - Camera Started Succesfully
[ INFO] [1476987945.871967607]: /camera/driver - Stopping camera
[ INFO] [1476987945.885350664]: /camera/driver - Camera Stopped Succesfully
[ INFO] [1476987945.885702175]: /camera/driver - Starting camera
[ INFO] [1476987945.904206693]: /camera/driver - Camera Started Succesfully
[ INFO] [1476987946.120719491]: /camera/driver - Stopping camera
[ INFO] [1476987946.133510992]: /camera/driver - Camera Stopped Succesfully
[ INFO] [1476987946.134155557]: /camera/driver - Camera is already Stopped
[ INFO] [1476987946.135913951]: /camera/driver - Starting camera
[ INFO] [1476987946.154492640]: /camera/driver - Camera Started Succesfully
[ERROR] [1476987951.154716202]: /camera/driver - Error calling rs_wait_for_frames ( device:0xc2b478 ): 
Timeout waiting for frames. 

Traceback (most recent call last):
  File "/home/ur5/ur5_ws/src/ur_grasping/scripts/camera_test.py", line 23, in <module>
    main()
  File "/home/ur5/ur5_ws/src/ur_grasping/scripts/camera_test.py", line 20, in main
    camera_forcepower_service(False)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 435, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 495, in call
    service_uri = self._get_service_uri(request)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 463, in _get_service_uri
    raise ServiceException("service [%s] unavailable"%self.resolved_name)
rospy.service.ServiceException: service [/camera/driver/force_power] unavailable
[camera/camera_nodelet_manager-1] process has died [pid 28107, exit code 1, cmd /opt/ros/indigo/lib/nodelet/nodelet manager __name:=camera_nodelet_manager __log:=/home/ur5/.ros/log/8c6d86ce-96e6-11e6-96fb-
4ccc6a230519/camera-camera_nodelet_manager-1.log].
log file: /home/ur5/.ros/log/8c6d86ce-96e6-11e6-96fb-4ccc6a230519/camera-camera_nodelet_manager-1*.log
[camera_test-16] process has died [pid 28231, exit code 1, cmd /home/ur5/ur5_ws/src/ur_grasping/scripts/camera_test.py __name:=camera_test __log:=/home/ur5/.ros/log/8c6d86ce-96e6-11e6-96fb-4ccc6a230519/cam
era_test-16.log].
```

**Comment by mattcorsaro1** [comment]
I tried running it again, and got the other error, which requires a computer reboot:

```
ur5@UR5:~/ur5_ws/src/librealsense/bin$ roslaunch ur_grasping camera_test.launch 
... logging to /home/ur5/.ros/log/a7896c82-97b5-11e6-b068-4ccc6a230519/roslaunch-UR5-11078.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://UR5:39941/

SUMMARY
========

PARAMETERS
 * /camera/camera_nodelet_manager/num_worker_threads: 4
 * /camera/depth_rectify_depth/interpolation: 0
 * /camera/disparity_depth/max_range: 4.0
 * /camera/disparity_depth/min_range: 0.5
 * /camera/disparity_registered_sw/max_range: 4.0
 * /camera/disparity_registered_sw/min_range: 0.5
 * /camera/driver/base_frame_id: camera_link
 * /camera/driver/camera_type: SR300
 * /camera/driver/color_fps: 30
 * /camera/driver/color_frame_id: camera_rgb_frame
 * /camera/driver/color_height: 480
 * /camera/driver/color_optical_frame_id: camera_rgb_optica...
 * /camera/driver/color_width: 640
 * /camera/driver/depth_fps: 30
 * /camera/driver/depth_frame_id: camera_depth_frame
 * /camera/driver/depth_height: 480
 * /camera/driver/depth_optical_frame_id: camera_depth_opti...
 * /camera/driver/depth_width: 640
 * /camera/driver/enable_color: True
 * /camera/driver/enable_depth: True
 * /camera/driver/enable_pointcloud: False
 * /camera/driver/enable_tf: True
 * /camera/driver/ir2_frame_id: camera_ir2_frame
 * /camera/driver/ir_frame_id: camera_ir_frame
 * /camera/driver/mode: manual
 * /camera/driver/serial_no: 
 * /camera/driver/usb_port_id: 
 * /camera/points_xyzrgb_sw_registered/queue_size: 100
 * /rosdistro: indigo
 * /rosversion: 1.11.20

NODES
  /camera/
    camera_nodelet_manager (nodelet/nodelet)
    depth_metric (nodelet/nodelet)
    depth_metric_rect (nodelet/nodelet)
    depth_points (nodelet/nodelet)
    depth_rectify_depth (nodelet/nodelet)
    depth_registered_sw_metric_rect (nodelet/nodelet)
    disparity_depth (nodelet/nodelet)
    disparity_registered_sw (nodelet/nodelet)
    driver (nodelet/nodelet)
    ir_rectify_ir (nodelet/nodelet)
    points_xyzrgb_sw_registered (nodelet/nodelet)
    register_depth_rgb (nodelet/nodelet)
    rgb_debayer (nodelet/nodelet)
    rgb_rectify_color (nodelet/nodelet)
    rgb_rectify_mono (nodelet/nodelet)
  /
    camera_test (ur_grasping/camera_test.py)

auto-starting new master
process[master]: started with pid [11090]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to a7896c82-97b5-11e6-b068-4ccc6a230519
process[rosout-1]: started with pid [11103]
started core service [/rosout]
process[camera/camera_nodelet_manager-2]: started with pid [11106]
process[camera/driver-3]: started with pid [11107]
process[camera/rgb_debayer-4]: started with pid [11108]
process[camera/rgb_rectify_mono-5]: started with pid [11109]
process[camera/rgb_rectify_color-6]: started with pid [11110]
process[camera/ir_rectify_ir-7]: started with pid [11111]
process[camera/depth_rectify_depth-8]: started with pid [11112]
process[camera/depth_metric_rect-9]: started with pid [11113]
process[camera/depth_metric-10]: started with pid [11114]
process[camera/depth_points-11]: started with pid [11115]
process[camera/register_depth_rgb-12]: started with pid [11116]
process[camera/points_xyzrgb_sw_registered-13]: started with pid [11117]
process[camera/depth_registered_sw_metric_rect-14]: started with pid [11118]
process[camera/disparity_depth-15]: started with pid [11119]
process[camera/disparity_registered_sw-16]: started with pid [11120]
process[camera_test-17]: started with pid [11121]
[ INFO] [1477071716.259051994]: Initializing nodelet with 4 worker threads.
[ INFO] [1477071718.422540242]: /camera/driver - Detected the following cameras:
                - Serial No: 612201004240, USB Port ID: 8-1, Name: Intel RealSense SR300, Firmware: 3.15.0.0
[ INFO] [1477071718.422618814]: /camera/driver - Connecting to camera with Serial No: 612201004240, USB Port ID: 8-1
[ INFO] [1477071718.692741642]: /camera/driver - Setting static camera options
[ INFO] [1477071718.697593725]: /camera/driver - Enabling Color in manual mode
[ INFO] [1477071718.698850729]: /camera/driver - Enabling Depth in manual mode
[ INFO] [1477071718.699304348]: /camera/driver - Enabling IR in manual mode
[ INFO] [1477071718.699758526]: /camera/driver - Starting camera
[ INFO] [1477071718.720401793]: /camera/driver - Publishing camera transforms
[ INFO] [1477071718.720674035]: /camera/driver - Setting dynamic camera options
[ INFO] [1477071719.209781832]: /camera/driver - Camera is already Started
[ INFO] [1477071719.242555274]: /camera/driver - Camera is already Started
[ INFO] [1477071719.275926417]: /camera/driver - Camera is already Started
[ INFO] [1477071719.309297979]: /camera/driver - Camera is already Started
[ INFO] [1477071719.388216744]: /camera/driver - Camera is already Started
[ INFO] [1477071719.423755132]: /camera/driver - Stopping camera
[ INFO] [1477071724.452418134]: /camera/driver - Camera Stopped Succesfully
[ INFO] [1477071724.460465806]: /camera/driver - Camera is already Stopped
[ INFO] [1477071724.462096809]: /camera/driver - Starting camera
[ERROR] [1477071724.463308206]: /camera/driver - Error calling rs_start_device ( device:0x25a04e8 ): 
VIDIOC_S_FMT error 19, No such device 

Traceback (most recent call last):
  File "/home/ur5/ur5_ws/src/ur_grasping/scripts/camera_test.py", line 23, in <module>
    main()
  File "/home/ur5/ur5_ws/src/ur_grasping/scripts/camera_test.py", line 20, in main
    camera_forcepower_service(False)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 435, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 495, in call
    service_uri = self._get_service_uri(request)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 463, in _get_service_uri
    raise ServiceException("service [%s] unavailable"%self.resolved_name)
rospy.service.ServiceException: service [/camera/driver/force_power] unavailable
[camera_test-17] process has died [pid 11121, exit code 1, cmd /home/ur5/ur5_ws/src/ur_grasping/scripts/camera_test.py __name:=camera_test __log:=/home/ur5/.ros/log/a7896c82-97b5-11e6-b068-4ccc6a230519/camera_test-17.log].
log file: /home/ur5/.ros/log/a7896c82-97b5-11e6-b068-4ccc6a230519/camera_test-17*.log
[camera/camera_nodelet_manager-2] process has died [pid 11106, exit code 1, cmd /opt/ros/indigo/lib/nodelet/nodelet manager __name:=camera_nodelet_manager __log:=/home/ur5/.ros/log/a7896c82-97b5-11e6-b068-4ccc6a230519/camera-camera_nodelet_manager-2.log].
log file: /home/ur5/.ros/log/a7896c82-97b5-11e6-b068-4ccc6a230519/camera-camera_nodelet_manager-2*.log
[camera/driver-3] process has finished cleanly
log file: /home/ur5/.ros/log/a7896c82-97b5-11e6-b068-4ccc6a230519/camera-driver-3*.log
```

**Comment by mdhorn** [comment]
Starting the camera and then only  having a 1/10 of second before turning it off, and then no wait before turning it back on again doesn't seem like a reasonable test case.

Can you repeat this problem if you have a more reasonable use-case sleep times between the starts and stops?

`while True:`
`rospy.sleep(10.0)`
`camera_forcepower_service(True)`
`rospy.sleep(10.0)`
`camera_forcepower_service(False)`

**Comment by mattcorsaro1** [comment]
It does work if I add a bigger delay.
