### ISSUE TITLE
Build failed (lib version is 2.10.1). Odroid XU4. Ubuntu 16.04

### ISSUE THREAD

**Issue by manusovich** [realsenseai/realsense-ros#340]
Trying to build wrapper and it is failing with error below. Lib examples works well
```
Scanning dependencies of target realsense2_camera_generate_messages
[ 95%] Built target realsense2_camera_generate_messages
/home/odroid/catkin_ws/src/realsense/realsense2_camera/src/base_realsense_node.cpp:380:0: warning: ignoring #pragma omp parallel [-Wunknown-pragmas]
 #pragma omp parallel for schedule(dynamic)
 ^
x^CTraceback (most recent call last):
  File "/opt/ros/kinetic/bin/catkin_make", line 296, in <module>
    sys.exit(main())
  File "/opt/ros/kinetic/bin/catkin_make", line 240, in main
    run_command(cmd, make_path)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/catkin/builder.py", line 239, in run_command
    proc.wait()
  File "/usr/lib/python2.7/subprocess.py", line 1392, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/usr/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
    return func(*args)

```

**Comment by manusovich** [comment]
Closing issue because i just figured that out. Just in case if someone will have similar issue, that is because of lack of memory on the board. Check that you have at least 4 gig of memory to compile ros wrapper. In my case i had only 2 and additional 2-3 you can make by create swap file - 
```
$ cd /

$ sudo dd if=/dev/zero of=swapfile bs=1M count=3000

To set it as 1GB, change the count value (3000 in the example above) to 1000, 1500 for 1.5GB etc.

Now change the file created to a swap file with the command below.

$ sudo mkswap swapfile

Turn on the swap file with the command,

$ sudo swapon swapfile

To ensure that the swap file is turned on automatically at system startup, open fstab.

$ sudo nano etc/fstab

And add the line given below. Save and close.

/swapfile none swap sw 0 0

That is it. You can check if the system is using the swap file you created with the command

$ cat /proc/meminfo
```
